spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:duckchat_dev}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: never
      encoding: UTF-8

server:
  port: 8090
  servlet:
    context-path: /api

# 개발 환경에서는 보안 설정 간소화
security:
  basic:
    enabled: false

# JWT 설정
jwt:
  secret: ${JWT_SECRET:dummy_jwt_secret_key_for_development_environment}
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 604800

# OpenAI API 설정
openai:
  api:
    key: ${OPENAI_API_KEY:dummy-api-key}
    url: https://api.openai.com/v1/chat/completions

# CORS 설정
cors:
  allowed-origins: http://localhost:5173,http://localhost:8080,http://localhost:8082
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600

logging:
  level:
    root: INFO
    com.duckchat.api: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
