spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:duckchat}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
      encoding: UTF-8

server:
  port: ${SERVER_PORT:8090}
  address: 0.0.0.0
  servlet:
    context-path: /

jwt:
  secret: ${JWT_SECRET:duckchatdeals_secret_key_should_be_longer_in_production}
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 604800

cors:
  allowed-origins: http://localhost:8080
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600

openai:
  api:
    key: ${OPENAI_API_KEY:dummy-api-key}
    url: https://api.openai.com/v1/chat/completions

youtube:
  api:
    key: ${YOUTUBE_API_KEY:}

# Upload dir for temporary audio files. In production, set this to a secure directory
app:
  upload:
    dir: ${APP_UPLOAD_DIR:/tmp/duckchat-uploads}
